### Get all users
GET http://localhost:8080/api/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwaGlAZ21haWwuY29tIiwiaWF0IjoxNTk2OTY0NzY5LCJleHAiOjE1OTcwNTExNjl9.jrL-GF_zDY5XX_CIk2LtAVPDmE1y25KGhtwwo_Edy_Zk5tWVz9s3MQumrD8lSOj_CL2RNT1c2jkgY8M9VXag8A
