### Get all users
GET http://localhost:8080/api/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE1OTY2NDcwMzEsImV4cCI6MTU5NjczMzQzMX0.Qo8g5W2IlS1o4R00uODf9oZoKHCPaHqJHm6w-qxNRvoLD8935Inoe4hCDHVT9RAtUYPAPn0HDy72eX7heKnICA
