### Get all users
GET http://localhost:8080/api/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJpYXQiOjE1OTY5NjU1NTAsImV4cCI6MTU5NzA1MTk1MH0.YP2IVbT0LcPiLIKY4HAXLzFZ2ig_D9ZeEx_8VrUtk-3Djj1UssgjbUQOt-9FZAMTRYy3h77EoA4MBFbJfvaGew
